[General]
	configVersion = 2

[Drawers]
	[Drawers.Detached]
		heavyDrawers = true

	[Drawers.Filled]
		heavyDrawers = true

[Upgrades]
	[Upgrades.CreativeStorage]
		enableUpgrade = false

	[Upgrades.CreativeVending]
		enableUpgrade = false