name = "the-solar-apocalypse"
author = "SeriousFreezing"
version = "34.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "abd5d375cd97d24bd7054bdbd416911ebe177bcc7a661a5fbad51b53c0f71c50"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"

[options]
acceptable-game-versions = ["1.21.8", "1.21.11", "26.1"]
