name = "the-solar-apocalypse"
author = "SeriousFreezing"
version = "24.0+alpha"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7d9d6c65eee635a42effadb4153ff7e57dc77f7dfa7d8be05963f967fc8bbae4"

[versions]
fabric = "0.16.14"
minecraft = "1.21.8"

[options]
acceptable-game-versions = ["1.21.1", "1.21.6", "1.21.7", "1.21.8"]
