name = "the-solar-apocalypse"
author = "SeriousFreezing"
version = "28.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eaf37ef9897c21f4ee2e3829c986d9d873803647b63e6203945da58943044791"

[versions]
fabric = "0.18.3"
minecraft = "1.21.10"

[options]
acceptable-game-versions = ["1.21.9"]
