[digSpots]
    afterDiggingCooldownSeconds = 900.0
    minimumDistanceBetween = 160
    spawnDistance = 40
    spawnIntervalSeconds = 600.0
[dropRush]
    enabled = false
[fishingSpots]
    afterFishingCooldownSeconds = 900.0
    minimumDistanceBetween = 160
    secondsUntilLured = 3.0
    spawnDistance = 12
    spawnIntervalSeconds = 600.0
[goldRush]
    baseChance = 0.01